

                         expression  ::=  arithmeticExpression ;


               arithmeticExpression  ::=  "(" arithmeticExpression ")"
                       
                                       |  arithmeticExpression ( "+" | "-" | "×" | "÷" ) arithmeticExpression
                       
                                       |  arithmeticTerm

                                       |  [name]
                       
                                       ;

