

                         expression  ::=  arithmeticExpression ;


               arithmeticExpression  ::=  "(" arithmeticExpression ")"
                       
                                       |  type ( "+" | "-" | "×" | "÷" ) type

                                       |  arithmeticExpression ( "+" | "-" | "×" | "÷" ) arithmeticExpression
                       
                                       |  arithmeticTerm

                                       ;

