

                         expression  ::=  arithmeticExpression ;


               arithmeticExpression  ::=  arithmeticExpression ( "+" | "-" | "×" | "÷" ) arithmeticExpression
                       
                                       |  arithmeticTerm

                                       |  typeName
                       
                                       ;

