

                         statement  ::=  arithmeticAtatement ;


               arithmeticAtatement  ::=  type ( "<" | "<=" | ">=" | ">" ) type

                                      |  arithmeticExpression ( "<" | "<=" | ">=" | ">" ) arithmeticExpression

                                      ;
