

                         statement  ::=  arithmeticAtatement ;


               arithmeticAtatement  ::=  type ( "<" | "<=" | ">=" | ">" ) type

                                      |  arithmeticTerm ( "<" | "<=" | ">=" | ">" ) arithmeticTerm

                                      ;
