

                       term  ::=  "-"<NO_WHITESPACE>argument (100) ;


                       term  ::=  argument ( "÷" (99)

                                           | "×" (98)

                                           | "+" (97)

                                           | "-" (96) ) argument ;

