

                       term  ::=  "-"<NO_WHITESPACE>argument (50) ;


                       term  ::=  argument ( "÷" (14)

                                           | "×" (13)

                                           | "+" (12)

                                           | "-" (11) ) argument ;

