

                       term  ::=  arithmeticTerm ;


             arithmeticTerm  ::=  argument ( "+" | "-" | "×" | "÷" ) argument 

                               |  "(" argument ")"

                               ;
